'use client';

import Link from 'next/link';
import Footer from '@/components/Footer';

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <div className="flex items-center mb-8">
          <Link 
            href="/"
            className="flex items-center text-[#ffc62d] hover:text-[#e5b228] transition-colors"
          >
            <svg className="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Home
          </Link>
        </div>

        <h1 className="text-3xl md:text-4xl font-bold text-white mb-8">Terms & Conditions</h1>
        
        <div className="space-y-6 text-gray-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-4">Disclaimer - Terms & Conditions of www.ascendantacademy.ca</h2>
            <p>By using any of our Services (even just browsing one of our websites), you're agreeing to the following Terms and Conditions. If you don't agree with the Terms, you may not use our Services.</p>
            <p className="mt-4">These Terms and Conditions of Service and Use of www.ascendantacademy.ca (the "Terms and Conditions") are hereby made effective as of Jan 1, 2020 and last updated June 26, 2024 by Ascendant Academy, Inc., a Delaware corporation ("Ascendant Academy" or "we" or "us" or "our"), and, without waiving or otherwise releasing any right or obligation under any prior terms and conditions of the use of www.ascendantacademy.ca, hereby amend and restate any such prior terms and conditions.</p>
            <p className="mt-4">www.ascendantacademy.ca, and all related content, materials and services (collectively, the "Site") is an online resource related to the trading of securities and digital currencies that provides its customers and members with interactive chat rooms, trading, investment and research tools and simulators, and educational classes, materials and resources for use by customers and members in connection with their trading activities. "Securities" as used herein and for the purposes of these Terms and Conditions, shall include but not be limited to, money, securities, digital currencies, commodities and other investments of every kind and nature and all contracts and options relating thereto, whether for present or future delivery.</p>
            <p className="mt-4">In consideration of each member or customer's (each, a "customer" or "you") access to and use of the Site, we require every members and customer to act with integrity, to our rules for the Site, and to abide by these Terms and Conditions and each other rule, regulation or other policy of Ascendant Academy.</p>
            <p className="mt-4">You agree to read these Terms and Conditions carefully and retain them for future reference. You understand, acknowledge and agree that these Terms and Conditions govern all aspects of my use of the Site and the products and services of Ascendant Academy. By clicking "I AGREE" and/or using or accessing the Site, you acknowledge that you have received, read and understood these Terms and Conditions and the Privacy Policy of Ascendant Academy. If you are unwilling to be bound by these Terms and Conditions, you will not click "I AGREE" and/or use or access the Site. YOU UNDERSTAND, ACKNOWLEDGE AND AGREE THAT CLICKING "I AGREE" IS THE LEGAL EQUIVALENT OF YOU MANUALLY SIGNING THESE TERMS AND CONDITIONS, AND THAT YOU WILL BE LEGALLY BOUND BY THESE TERMS AND CONDITIONS.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">I. General Terms</h2>
            <p>By clicking "I AGREE" and/or using or accessing the Site, you thereby agree, (a) that you have received, read and understood these Terms and Conditions, and that these Terms and Conditions create a valid and binding agreement, enforceable against you in accordance with the terms hereof, (b) to be bound by these Terms and Conditions, any terms, conditions or other rules, regulations or policies of Ascendant Academy, as each may be amended or supplemented from time to time in our sole discretion without notice, and (c) that your use of the Site shall comply with all applicable federal, state and local laws, rules or regulations, and that you are solely responsible for your compliance with, familiarity with and understanding of any such laws, rules or regulations applicable to your use of the Site. If you do not agree with any portion of these Terms and Conditions, you are prohibited from using or accessing the Site.</p>
            
            <p className="mt-4">Additionally, and without limiting the foregoing, by using or accessing the Site, you represent and warrant to us that you: (a) are eighteen (18) years of age or older, (b) are not currently restricted from using the Site, or not otherwise prohibited from having an account with us, (c) are not a competitor of Ascendant Academy, or engaged in any business or activity, directly or indirectly, that could be competitive with the business or activities of Ascendant Academy, and are not using the Site for any reason that may be in competition with the Site or any other product or service offered by Ascendant Academy, (d) have full power and authority to enter into and perform these Terms and Conditions, and doing so will not violate any other agreement to which you are a party, (e) will not violate any rights of Ascendant Academy, including, without limitation, intellectual property rights such as patent, copyright or trademark rights, and (f) agree to provide, operate and maintain, at your sole risk, cost and expense, all equipment, software, and internet access necessary to use the Site.</p>

            <div className="mt-4 space-y-2">
              <p className="font-semibold">Without limiting the generality of the foregoing or any other provision hereof, you acknowledge and agree, as follows:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Not to promote, offer for sale or sell any product or service, including, without limitation, any financial or investment product, security or service, or any contest or promotion;</li>
                <li>That the content, materials, services and other intellectual property contained or embodied in the Site are owned by Ascendant Academy and are protected by patent, copyright, trademark and other similar laws;</li>
                <li>Not to transmit, send or otherwise post unauthorized commercial communications (such as spam), or other similar materials or advertisements, using the Site;</li>
                <li>Not to access the Site using any automated means, including, without limitation, harvesting bots, robots, spiders, or scrapers;</li>
                <li>Not to engage in multi-level marketing using the Site, including, without limitation, pyramid schemes and similar marketing concepts;</li>
                <li>Not to upload, use or disseminate viruses or other malicious code or other abusive scripts or processes;</li>
                <li>Not to solicit login, account or other personal information of another person or request or obtain access to an account of another person;</li>
                <li>Not to bully, intimidate, or harass any person;</li>
                <li>Not to post content that is hateful, threatening, or pornographic, incites violence, or contains nudity, graphic material, gratuitous violence or anything else found to be objectionable by Ascendant Academy in its sole discretion;</li>
                <li>Not to use the Site in any manner that is, or could reasonably be construed to be, unlawful, including, without limitation, in violation of any law, rule or regulation related to securities or investments, or any rules or regulations promulgated by the U.S. Securities and Exchange Commission, and/or rules of any national or other securities exchange and any regulations or other pronouncements having the force of law;</li>
                <li>Not to use the Site in any manner that is, or could reasonably be construed to be, in violation of these Terms and Conditions, fraudulent, misleading, malicious or discriminatory;</li>
                <li>Not to take any action that could disable, overburden, or impair the operation or availability of the Site, such as a denial of service attack;</li>
                <li>Not to engage in manipulative practices designed to obfuscate the true intent of your submissions to the Site, or to artificially generate traffic to another website;</li>
                <li>Not to facilitate or encourage any violations of these Terms and Conditions;</li>
                <li>Not to post or make any defamatory, disparaging or false statements, claims or allegations related to the Site, Ascendant Academy, or any other product or service of Ascendant Academy;</li>
                <li>Not to make your account or any portion thereof or the services provided thereby available to the general public or any portion thereof;</li>
                <li>Not to issue chargeback disputes against Ascendant Academy;</li>
                <li>Not to use patented, copyrighted, trademarked or other protected intellectual property without the written consent and authorization of the owner of such property;</li>
                <li>Not to copy, distribute or disseminate the Site or any portion thereof, and not to transfer the Site, or any portion thereof, to another person or "mirror" the Site, or any portion thereof, on any other server;</li>
                <li>Not to decompile or reverse engineer, or attempt to decompile or reverse engineer, the Site or any portion thereof;</li>
                <li>Not to take any other action that could result in any damage or disruption to the Site, or that could otherwise result in any liability, damages, costs or expenses on the part of Ascendant Academy;</li>
                <li>Not to share personal information with members, or request personal information from members.</li>
              </ul>
              <p className="mt-4">All content, materials and services related to the Site shall be solely used for, and you hereby agree to solely use it for, your own personal use in connection with your trading activities, and for no other use.</p>
              <p className="mt-4 font-semibold text-[#ffc62d]">Violating any of the aforementioned will result in immediate removal from Ascendant Academy and forfeits your right to request a refund.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">II. Ownership; Limited License</h2>
            <p>By becoming a customer of Ascendant Academy and using the Site, Ascendant Academy hereby grants to you a limited revocable license to use the Site, and its content, materials and services, solely for your personal use and for the purposes set forth on the Site, and subject to these Terms and Conditions and all other rules, regulations and policies imposed or adopted by Ascendant Academy in connection with the Site, which may be amended by Ascendant Academy at any time in its sole discretion and without notice. Such limited revocable license is freely revocable and terminable by Ascendant Academy at any time, without cause and in the sole discretion of Ascendant Academy. Without limiting the foregoing, this limited revocable license shall automatically be revoked and terminated upon any violation of these Terms and Conditions or any other rule, regulation or policy of Ascendant Academy. Upon revocation or termination of this limited revocable license, you shall, and hereby agree to, destroy any materials (electronic or otherwise) related to the Site that remain in your possession or control, and acknowledge that after such revocation or termination Ascendant Academy may deny your access to the Site and any other Ascendant Academy content, materials or services in its sole discretion. Any personal information of a user whose limited revocable license is revoked or terminated by Ascendant Academy will be preserved or disposed of in accordance with the terms of the Privacy Policy of Ascendant Academy. Any information you submit to Ascendant Academy is at your own risk of loss, and Ascendant Academy assumes no liability or responsibility therefor.</p>
            
            <p className="mt-4">Ascendant Academy reserves all rights not expressly granted in these Terms and Conditions, including, without limitation, title, ownership, intellectual property rights, and all other right, title and interest in and to the Site, the products and services of Ascendant Academy, and all related content, materials, services, and other documents, information or items, including any copies or derivative works thereof. You acknowledge and agree that the Site, the products and services of Ascendant Academy, and all related content, materials, services, and other documents, information or items, including any copies or derivative works thereof, is owned by Ascendant Academy, and is protected by copyright, trademark and other intellectual property laws. You further acknowledge and agree that the Site, the products and services of Ascendant Academy, and related content, materials, services, and other documents, information or items, including any copies or derivative works thereof, contains certain proprietary data and information of Ascendant Academy, that you will not use this data or information for any unlawful or unauthorized purpose, and that you will use reasonable efforts to protect them from illicit distribution or use.</p>
            
            <p className="mt-4">Additionally, you grant Ascendant Academy an exclusive, irrevocable, worldwide, perpetual, unlimited, freely assignable and sublicenseable, fully paid up and royalty-free right to use, copy, prepare derivative works of, improve, distribute, publish, remove, retain, add, process, analyze and commercialize, in any way now known or in the future discovered, any information, content, ideas, concepts, techniques, data or suggestions submitted to the Site for the purpose of improving or modifying the Site, or any content, materials or services, or for the purpose of creating or developing new content, materials, services or product related to, arising from or ancillary or similar to the Site, without any further consent, notice and/or compensation to you or to any third parties.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">III. Consent to Utilize Audio, Video and Photography from Events</h2>
            <p>Ascendant Academy may host events from time to time. These events may be recorded and photographed for marketing and/or the production of educational content. By attending Ascendant Academy events, you agree to allow Ascendant Academy to utilize audio, video, and photographs that you may appear in. This includes our Discord Community.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">IV. Violation; Termination of Account</h2>
            <p>Ascendant Academy reserves the right to investigate violations of any of these Terms and Conditions or any other policies of Ascendant Academy or the Site, or any other violations of any state, federal or local law, rule or regulation, and to pursue any remedy available to Ascendant Academy whether at law, in equity or otherwise. You hereby acknowledge and agree that Ascendant Academy may notify, involve and cooperate with law enforcement authorities in investigating and prosecuting users who violate these Terms and Conditions or any other policies of Ascendant Academy or the Site, and any other violations of any state, federal or local laws, rules or regulations. You further acknowledge and agree that Ascendant Academy has no obligation to, and does not, screen or monitor any users, information, materials or other content provided or made available through the Site, but has the right to do so at any time in its sole discretion. You further acknowledge and agree that Ascendant Academy may, in its sole discretion, remove or delete any entries, information, materials or other content, and terminate the subscription, membership or account (collectively, your "account") of any user, that violates these Terms and Conditions or otherwise posts, submits, or disseminates content that Ascendant Academy finds, in its sole discretion, to be objectionable.</p>
            
            <p className="mt-4">You acknowledge and agree that Ascendant Academy may, in its sole discretion, cancel, suspend or terminate your account if you breach these Terms and Conditions. Ascendant Academy may refuse, in its sole discretion, to permit any use of the Site, and may refuse to permit any person to access or use the Site or your account for any reason at any time.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">V. Purchases and Refunds</h2>
            <p>Through the Site, Ascendant Academy offers both individual products for sale and subscription, membership or other periodic fee-based services. For individual products purchased through the Site, a valid credit card or other payment method will be required to complete the purchase and the amount of the purchase will be charged to the credit card concurrently with the completion of the purchase on the Site. When you purchase an individual product, you will receive a streaming or digital version; no physical copies of products or other materials will be shipped or provided to you.</p>
            
            <p className="mt-4">When purchasing subscription, membership or other periodic fee-based services on the Site, a valid credit card will be required for billing purposes. You hereby consent to, acknowledge and allow Ascendant Academy to store (or cause a third party to store on behalf of Ascendant Academy) such payment information and agree to the following policies and procedures for payment of subscription, membership or other periodic fees related to the Site.</p>
            
            <p className="mt-4">If the credit card associated with your account or service should expire, terminate or any payment is otherwise rejected by the issuing company, Ascendant Academy may immediately terminate your account or service. It is solely your responsibility to ensure (1) that valid credit card information remains on file for your account or service and the automatic renewal thereof, and (2) that a valid email address remains on file for your account or service for any communications from Ascendant Academy related thereto.</p>
            
            <p className="mt-4">All subscription payments made to Ascendant Academy in connection with any product purchased or account or service, and any renewal thereof, are non-refundable; and Ascendant Academy does not offer, and is not required to provide, any refunds or credits for any reason, including, without limitation, satisfaction or your failure to cancel your account or service prior to its automatic renewal. There is no circumstance in which you will be entitled to, or Ascendant Academy is required to provide, a refund or credit for any reason, including, without limitation, satisfaction or your failure to cancel your account or service prior to its automatic renewal.</p>
            
            <p className="mt-4">All Ascendant Academy digital course's & Premium Lifetime payments made to Ascendant Academy are subject to our 14 day refund policy which includes the following conditions:</p>
            
            <ol className="list-decimal list-inside space-y-2 ml-4 mt-4">
              <li>Refund requests must be submitted to support@ascendantacademy.ca within 14 Days (336 hours) of purchase. Users must include their information and reasoning for the refund request.</li>
              <li>The first 14 Day action plan must be completed in its entirety. This includes:
                <ul className="list-disc list-inside ml-8 mt-2 space-y-1">
                  <li>You must watch all lessons in full up to the "Proprietary Strategies Acknowledgment" in the Training Course and mark them complete in your dashboard. Once you acknowledge and pass the Proprietary Strategies Notice, you are no longer eligible for a refund. By proceeding beyond this point, you waive your right to request a refund under any circumstances, as you have accessed Ascendant Academy's proprietary and confidential materials.</li>
                  <li>Attend at least 2 mentoring sessions with your instructor (access within our Premium Discord community).</li>
                </ul>
              </li>
              <li>If, after completing the above you have a specific issue with the program you may be permitted a full refund.</li>
              <li>Personal reasons are NOT eligible for a refund.</li>
              <li>Trading performance reasons are NOT eligible for a refund.</li>
              <li>User technical issues must be resolved with the Ascendant Academy support team at support@ascendantacademy.ca.</li>
              <li>Purchases of Premium Lifetime are subject to the above 14 Day refund policy.</li>
            </ol>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">VI. Modifications</h2>
            <p>Ascendant Academy reserves the right to, and you acknowledge and agree that Ascendant Academy may, modify the Site, including without limitation the content, materials and services offered thereby, and the fees, costs and pricing associated with the Site at any time and without notice. Without limiting the generality of the foregoing, Ascendant Academy reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Site (or any part or portion thereof) without notice. Any new features that augment or enhance the then-current version of the Site, including the release of new tools and resources, shall be subject to these Terms and Conditions and may result, in Ascendant Academy's sole discretion, to a price increase. Ascendant Academy shall not be liable to you, or to any third party, for any damages, costs, expenses or other liabilities related to any modification, price change, suspension or discontinuance of the Site.</p>
            
            <p className="mt-4">Without limiting the foregoing, Ascendant Academy may use banner notices or similar devices to alert you to certain modifications to the Site or the pricing associated therewith. Alternatively, notice may consist of an email from Ascendant Academy or the Site to an email address associated with your account or service, even if we have other contact information. You also agree that Ascendant Academy may communicate with you through any available means including email, mobile number, telephone, or delivery services, including the postal service, about your account or service or any products or services associated with the Site. You acknowledge and agree that we shall have no liability associated with or arising from your failure to maintain accurate contact or other information, including, but not limited to, your failure to receive critical information about the Site or pricing.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">VII. Cancellations</h2>
            <p>Your account or service may be cancelled, subject to the terms hereof, at any time; provided that, as set forth above, no refunds will be issued if your account or other periodic fee-based service is cancelled prior to the end of the applicable period or term.</p>
            
            <p className="mt-4">When you cancel, you are solely responsible for properly canceling your account or service. Your account or service may be cancelled at any time by (i) clicking here or by clicking on the "Subscriptions" tab on the Member Dashboard, which is accessed, among other means, by the "Dashboard" tab at the top of the home page of the Site, and by following the onscreen prompts, or (ii) by requesting such cancellation in writing by email to support@ascendantacademy.ca, which cancellation request must receive a confirmation of receipt from Ascendant Academy and which cancellation will be processed by Ascendant Academy in accordance with its timelines and procedures for email cancellations. Cancellation requests by telephone, facsimile or other means of communication cannot, and will not, be accepted, honored or effective. The cancellation of your account or service will immediately result in the deactivation and deletion of your account or service, the denial of access to the Site and the forfeiture and relinquishment of all content and information within or related to your account or service. No data, content or information can be recovered once your account or service is cancelled, and you assume all responsibility for preserving any data, content or information on your account or service prior to its cancellation. Ascendant Academy may retain data, content or information from your account after cancellation in backup and/or archival copies of the Site and related databases, but such copies, if any, will not be available to you.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">VIII. General Disclaimer of Warranties</h2>
            <p className="font-bold">THE SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITH NO WARRANTIES WHATSOEVER.</p>
            
            <p className="mt-4 font-bold">ASCENDANT ACADEMY DISCLAIMS TO THE FULLEST EXTENT PERMITTED BY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS. WITHOUT LIMITING THE FOREGOING, ASCENDANT ACADEMY DISCLAIMS ANY WARRANTIES REGARDING THE SECURITY, RELIABILITY, AVAILABILITY, SERVICE LEVELS, TIMELINESS, AND PERFORMANCE OF THE SITE; ASCENDANT ACADEMY DISCLAIMS ALL LIABILITY FOR ANY CLAIMS, DAMAGES, LOSSES, COSTS OR EXPENSES (INCLUDING ATTORNEY'S FEES) RELATED TO THE FOLLOWING, AND DOES NOT WARRANT THAT (I) THE SITE WILL MEET YOUR SPECIFIC REQUIREMENTS, (II) THE SITE WILL BE UNINTERRUPTED, TIMELY, AVAILABLE, SECURE OR ERROR-FREE, (III) THAT ANY RESULTS MAY BE OBTAINED FROM YOUR USE OF THE SITE, OR THAT ANY DATA, CONTENT OR INFORMATION ON THE SITE IS, OR WILL BE, VALID, ACCURATE, TIMELY, ADEQUATE, COMPLETE, LEGAL OR OTHERWISE RELIABLE, (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SITE WILL MEET YOUR EXPECTATIONS, OR (V) ANY ERRORS IN THE SITE WILL BE CORRECTED.</p>
            
            <p className="mt-4 font-bold">ASCENDANT ACADEMY DISCLAIMS ANY WARRANTIES FOR ANY INFORMATION, CONTENT OR ADVICE OBTAINED THROUGH THE SITE; AND, ASCENDANT ACADEMY DISCLAIMS ANY WARRANTIES FOR SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE SITE OR RECEIVED THROUGH ANY LINKS PROVIDED BY THE SITE.</p>
            
            <p className="mt-4 font-bold">YOU UNDERSTAND, ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE SITE, AND ANY CONTENT, SERVICES OR OTHER INFORMATION OR MATERIALS RELATED THERETO, IS SOLELY AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY LIABILITY, CLAIM, DAMAGES, LOSS, COST OR EXPENSE, THAT RESULTS FROM OR ARISES FROM YOUR USE OF THE SITE, OR ANY CONTENT, SERVICES OR OTHER INFORMATION OR MATERIALS RELATED THERETO. YOU HEREBY EXPRESSLY DISCLAIM AND RELEASE AND WAIVE ANY LIABILITY, CLAIM, DAMAGES, LOSS, COST OR EXPENSE, RELATED TO OR ARISING FROM, THE WARRANTIES DISCLAIMED BY ASCENDANT ACADEMY HEREBY.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">IX. Disclaimers</h2>
            <p className="font-bold">ASCENDANT ACADEMY EXPRESSLY DISCLAIMS AND DISCLOSES AS FOLLOWS, AND YOU HEREBY CONFIRM THAT YOU UNDERSTAND, ACKNOWLEDGE AND AGREE AS FOLLOWS, AND EXPRESSLY DISCLAIM, RELEASE AND WAIVE ANY LIABILITY, CLAIM, DAMAGES, LOSS, COST OR EXPENSE, INCONSISTENT WITH, RELATED TO OR ARISING FROM THE FOLLOWING:</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Your Responsibility</h3>
            <p>Ascendant Academy is not registered as an investment adviser with the U.S. Securities and Exchange Commission. Rather, Ascendant Academy relies upon the "publisher's exclusion" from the definition of "investment adviser" as provided under Section 202(a)(11) (D) of the Investment Advisers Act of 1940 and corresponding state laws. As such, Ascendant Academy does not offer or provide personalized investment advice. To the extent any of the content, material, information and/or any other kind of informational offering published, broadcast, or otherwise stated on this, and/or associated websites, may be deemed to be "investment advice", such information is impersonal and not tailored to the investment needs of any specific person. The information contained within this, and/or, associated websites, is provided for informational and educational purposes only. The information should not be construed as investment or trading advice, and is not meant to be a solicitation or recommendation to buy, sell, or hold any positions in any indices or financial markets mentioned. The content and information provided by Ascendant Academy, the Site and the other products and services of Ascendant Academy, is solely incidental to the business and activities of Ascendant Academy in providing educational services.</p>
            
            <p className="mt-4">You remain solely responsible for all decisions regarding your purchase and sale of securities, the suitability, profitability or appropriateness for you of any security, investment, financial product, investment strategy or other matter, and all other matters related to your investments and investment strategies. Ascendant Academy does not and will not provide you with any legal, tax, estate planning or accounting advice, or any advice regarding the suitability, profitability or appropriateness for you of any security, investment, financial product, investment strategy or other matter. You understand, acknowledge and agree that Ascendant Academy employees are not authorized to give any such advice, you will neither solicit nor rely on any investment advice from any Ascendant Academy employee. Ascendant Academy recommends that persons desiring to trade or invest in securities do so cautiously and only in consultation with their professional, licensed and qualified financial, legal, tax, estate planning and accounting advisors.</p>
            
            <p className="mt-4">No data, content or information provided by Ascendant Academy, the Site or the other products and services of Ascendant Academy, is intended, and shall not constitute or be construed as, advice or any recommendation to buy or sell securities, nor any offer, or solicitation of an offer, to buy or sell securities, nor an attempt to influence the purchase or sale of any security. Ascendant Academy is not registered as an investment adviser either with the U.S. Securities and Exchange Commission, any other federal or national governmental or regulatory authority, or any state securities governmental or regulatory authority, and the business and activities of Ascendant Academy do not require any such registration.</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Research, Informational and Educational Purposes Only</h3>
            <p>Neither the Scanner, nor Ascendant Academy, offers or provides personalized investment advice. All data, content and information within the Scanner is impersonal and not tailored to the investment needs of any specific person. Such data, content and information is provided for research, informational and educational purposes only.</p>
            
            <p className="mt-4">The Scanner is provided to help you research and evaluate securities based on your individual criteria, sorting and inputs. Those individual criteria, sorting and inputs are controlled and entered solely by you. Use of the Scanner does not indicate or guaranty any predictable, general, specific or other results. The Scanner is only one of many ways that you may research and evaluate securities and you should not rely upon the Scanner, or any data, content and information therein, as the sole basis for an investment decision or transaction. If you choose to rely on the Scanner or any such data, content, or information, you understand, acknowledge, and agree that you are doing so solely at your own risk and bear sole responsibility for your own investment research and decisions. You remain solely responsible for all decisions and transactions regarding your purchase and sale of securities, the suitability, profitability or appropriateness for you of any security, investment, financial product, investment strategy or other matter, and all other matters related to your investments and investment strategies.</p>
            
            <p className="mt-4">Ascendant Academy does not and will not provide you with any legal, tax, estate planning or accounting advice, or any advice regarding the suitability, profitability or appropriateness for you of any security, investment, financial product, investment strategy or other matter. The data, content and information within the Scanner should not be construed as investment or trading advice, and is not meant to be a solicitation or recommendation to buy, sell, or hold any positions in any securities or to engage in any other transaction. Such data, content and information provided by the Scanner is solely incidental to our business and activities in providing educational services.</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Data, Content and Information</h3>
            <p>No data, content or information provided by Ascendant Academy, the Site or the other products and services of Ascendant Academy, is intended, and shall not constitute or be construed as, advice or any recommendation to buy, sell or hold a particular security or pursue any particular investment strategy.</p>
            
            <p className="mt-4">Ascendant Academy neither assumes responsibility for, nor guarantees the accuracy, currency, completeness or usefulness of information, commentary, recommendations, advice, investment ideas or other materials that may be accessed by you through the Site or the other products or services of Ascendant Academy. This includes, without limitation, any forum, chatroom or other online conference, telecast or posting through Ascendant Academy. If you choose to rely on such information, you understand, acknowledge and agree do so solely at your own risk. You understand, acknowledge and agree that the research, analysis, news or other information made available through the Site or the other products or services of Ascendant Academy is not investment advice and is in no way tailored to reflect any personal financial circumstances or investment objectives and the securities and investment strategies discussed may not be suitable for you. Any determination to purchase or sell securities or otherwise invest in securities must be made solely by you after your independent investigation and evaluation thereof based on your personal financials and other circumstances and without any reliance on the data, content or information provided by Ascendant Academy, the Site or the other products and services of Ascendant Academy.</p>
            
            <p className="mt-4">Ascendant Academy cannot, and does not, independently verify, assess or guarantee the validity, adequacy, timeliness, accuracy or completeness of any data, content or information, the suitability or profitability of any particular security or investment, or the potential value of any security, investment or informational source. You bear sole responsibility for your own investment research and decisions, and should seek the advice of a professional, licensed and qualified securities professional before purchasing or selling any security or making any investment.</p>
            
            <p className="mt-4">The forum and chatrooms on the Site are comprised of customers and members (including, without limitation, moderators who are in the employ of Ascendant Academy) posting content and information. All such information and content is for informational purposes only and does not constitute advice or a recommendation by Ascendant Academy to enter into any securities transactions or engage in any of the financial strategies reflected on or suggested in forum and chatrooms (whether such data, content or information is posted by Ascendant Academy or otherwise). Customers and members may write about securities in which they have a financial or other interest, and performance data reflecting other customer's or member's holdings may include information about securities not held by Ascendant Academy or its directors, officers, shareholders, employees, agents or affiliates. As such, Ascendant Academy is not responsible for the accuracy of data, content or information or any performance data in any forum or chatroom; and the accuracy of data, content or information or any performance data are not guaranteed, may not be current and should not be relied upon. Nothing in any forum or chatroom is intended as, nor should you rely on it as, investment advice provided by Ascendant Academy or its directors, officers, shareholders, employees, agents or affiliates.</p>
            
            <p className="mt-4">Ascendant Academy does not control, and does not endorse, any data, content or information posted on the forum or chatroom on the Site. You understand, acknowledge and agree that your participation therein is at your own risk, and Ascendant Academy expressly disclaims responsibility for any such data, content or information. Ascendant Academy has the right (but not the obligation) to review and take down any data, content or information. You understand, acknowledge and agree that by accessing the forum or chatroom on the Site, you may be exposed to material that you deem to be offensive, indecent, obscene or otherwise objectionable. Under no circumstances will you hold Ascendant Academy, or its directors, officers shareholders, employees, agents or affiliates, liable for any such content displayed or made available through the Site, or for any loss or damage of any kind incurred as a result of your use of the forum or chatroom on the Site.</p>
            
            <p className="mt-4">Without limiting the generality of the foregoing, you understand, acknowledge and agree that chat room moderators may call out or post both real and hypothetical trades and real and simulated or hypothetical returns for informational and educational purposes only. Moderator commentary is opinion and ideas only and does not constitute any recommendation whatsoever, and you should not relay on such opinions and ideas which may not be complete or accurate. Each of Ascendant Academy's services, products and site are available for informational and educational purposes only. None of the information contained in the site (which includes, without limitation, our alerts service and chat room) constitutes, or is intended to constitute, a recommendation by us of any particular security or trading strategy or a determination by us that any security or trading strategy is suitable for any specific person. We are publishers and educators only.</p>
            
            <p className="mt-4">You understand, acknowledge and agree that MODERATOR results may be based on simulated or hypothetical performance, and such results have certain inherent limitations. Unlike the results shown in an actual performance record, such results do not represent actual trading. Your actual results may differ from results reported for many reasons, including, without limitation: performance results do not reflect actual trading commissions that You may incur; performance results do not account for the impact, if any, of certain market factors, such as lack of liquidity, that may affect Your results; the investments chosen may be volatile, and server, delivery delays and other factors may cause the price You obtain to differ substantially from the price at the time of the alert; the prices of investments at the point in time You begin subscribing may be higher than such prices at the time such investments were chosen; You may not have the capital to trade as frequently as the moderator; and the size and timing of your purchase or sale of a stock may affect the price of the stock, among other reasons.</p>
            
            <p className="mt-4">You understand, acknowledge and agree that, For informational and teaching purposes only, trades may be called out, posted, or alerted, but not executed. You understand, acknowledge and agree that moderators may sometimes purchase or sell securities sooner or later than called out, posted or alerted. Moderators are also not required to disclose all trades, and their positions may be inconsistent with trades. Also, because some trades may not actually have been executed, results may have under-or-over-compensated for the impact, if any, of certain market factors, such as liquidity. Simulated or hypothetical trading programs in general are also subject to the fact that they are designed with the benefit of hindsight. You understand, acknowledge and agree that the Site contains simulated or hypothetical trading programs. No representation is being made that any account will or is likely to achieve profits or losses similar to these being shown.</p>
            
            <p className="mt-4">You understand, acknowledge and agree that Ascendant Academy and its directors, officers, shareholders, employees, agents and affiliates have no obligation to notify you as to which trades and returns are real versus simulated or hypothetical, and that Ascendant Academy, and its directors, officers, shareholders, employees, agents and affiliates do not verify moderator trade records or maintain records of moderator trades and results, and that moderators have no obligation to provide Ascendant Academy any data.</p>
            
            <p className="mt-4">Through your use of the site, You expressly contract and consent to the operations of Ascendant Academy (including the moderator actions and omissions discussed above) and release Ascendant Academy, and its directors, officers, shareholders, employees, agents and affiliates from any liability, claim, loss, cost, expense, and any other damages arising from or relating to moderator statements (written or oral), actions and omissions, including real, simulated, or hypothetical trades and results. Trading in any security can result in immediate and substantial losses of the money invested. you Should only invest funds that are not allocated for other purposes, such as retirement savings, student loans, mortgages, education, or debt reduction, and that you can afford to loose. Don't trade with money you can't afford to lose.</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Third-Party Data, Content and Information for Scanners</h3>
            <p>Data, content and information presented or available within the Scanner is provided to us by third-party providers. The securities included in the Scanner include only those that are currently identified by these third-party providers, and the Scanner includes only securities where data, content or information for such securities is provided to us by these third-party providers. All securities may not be available on the Scanner, and the Scanner may not provide all data, content and information for securities. We cannot, and do not, independently verify, assess or guarantee the validity, adequacy, timeliness, accuracy or completeness of any such data, content or information, the suitability or profitability of any particular security or investment, or the potential value of any security, investment or informational source. We do not control, and do not endorse, any such data, content or information, and neither assume responsibility for, nor guarantee the validity, adequacy, timeliness, accuracy, reliability, completeness or usefulness of, such data, content or information. We do not represent or warrant, and hereby disclaim, any representations or warranties of validity, adequacy, timeliness, accuracy, reliability, completeness or usefulness of such data, content or information, and that data, content or information will be timely, updated or available for all or certain securities within the Scanner.</p>
            
            <p className="mt-4">All such data, content or information is for informational purposes only and does not constitute advice or a recommendation by Ascendant Academy to enter into any securities transactions or engage in any financial strategies based upon such data, content or information. All such data, content and information is historical and is subject to revision or change at any time, and Ascendant Academy disclaims any obligation to timely update such data, content or information.</p>
            
            <p className="mt-4">The Scanner may contain links to other websites or applications containing additional data, content or information. Ascendant Academy does not control, and does not endorse, any such data, content or information, and neither assumes responsibility for, nor guarantees the validity, adequacy, timeliness, accuracy, reliability, completeness or usefulness of such data, content or information.</p>
            
            <p className="mt-4">You understand, acknowledge and agree that your use of the Scanner is at your own risk, and Ascendant Academy expressly disclaims all responsibility for any such data, content or information, and responsibility for any decisions based on such data, content or information, or for purchasing or selling any security or engaging in any investment or transaction, based on such data, content or information. You bear sole responsibility for your own investment research and decisions, and should seek the advice of a professional, licensed and qualified securities professional before purchasing or selling any security or engaging in any investment or transaction.</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Activities of Ascendant Academy Personnel</h3>
            <p>Ascendant Academy, and its directors, officers, shareholders, employees, agents and affiliates, are active investors and traders of securities. Such parties may, not are not required to, purchase or sell any security, or engage in any investment strategy, contained in any data, content or information on the Site, or in the other products or services of Ascendant Academy. Such parties will purchase or sell securities, and engage in any investment strategies, in their sole discretion, at any time and without notice, and shall not, and are not required to disclose or otherwise notify you, or any other person or party, with respect to any such decisions or activities. For the avoidance of doubt, such parties may not always adhere to Ascendant Academy strategies and are not required to disclose or notify you, or any other person or party, with respect to any such decisions or activities. Ascendant Academy personnel adhere to their unique individual plans developed and implemented by them with or without Ascendant Academy, and experiences will not be duplicated and are not typical.</p>
            
            <p className="mt-4">Ascendant Academy does not engage in, and its business and activities shall not constitute or be construed as, a business or activity with the purpose of creating a false or misleading appearance of active trading in any security, or a false or misleading appearance with respect to the market for such security, to effect any transaction in such security which involves no change in the beneficial ownership thereof, to enter an order or orders for the purchase of such security with the knowledge that an order or orders of substantially the same size, at substantially the same time, and at substantially the same price, for the sale of any such security, has been or will be entered by or for the same or different parties, or to enter any order or orders for the sale of any such security with the knowledge that an order or orders of substantially the same size, at substantially the same time, and at substantially the same price, for the purchase of such security, has been or will be entered by or for the same or different parties.</p>
            
            <p className="mt-4">Ascendant Academy does not engage in, and its business and activities shall not constitute or be construed as, a business or activity to effect a series of transactions creating actual or apparent active trading in a security, or raising or depressing the price of such security, for the purpose of inducing the purchase or sale of such security by others.</p>
            
            <p className="mt-4">Ascendant Academy does not engage in, and its business and activities shall not constitute or be construed as, a business or activity to effect a series of transactions for the purchase and/or sale of a security for the purpose of pegging, fixing, or stabilizing the price of such security in contravention of any law, rule or regulation.</p>
            
            <p className="mt-4">You understand, acknowledge and agree that Ascendant Academy, and its directors, officers, shareholders, employees, agents and affiliates, engage in active trading of securities, but do not willfully participate in any activity described in the three preceding paragraphs. Accordingly, you hereby waive and release any and all claims, losses, damages, liabilities and any other costs and expenses (including attorneys' fees), arising from or related to your purchase or sale of a security at a price that may have been affected by the business or activities of Ascendant Academy, or its directors, officers, shareholders, employees, agents or affiliates.</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Investments and Results</h3>
            <p>The purchase and sale of securities, digital currencies, futures, or commodities involve a high degree of risk and is speculative in nature. The purchase and sale of securities should only be conducted by persons who understand and accept the risks involved therewith and who have independently reviewed and determined their acceptance and suitability of these risks and the financial and tax consequences thereof. Only persons who are able to bear the risk of substantial or complete loss of funds should engage in the purchase and sale of securities, futures or commodities.</p>
            
            <p className="mt-4">Ascendant Academy, and the content and information contained on the Site, and in other products and services of Ascendant Academy, do not indicate or guaranty any predictable, general, specific or other results. The purchase and sale of securities, and any other investment activity, involves a high degree of risk, and a number of factors could materially and adversely affect the results and lead to a substantial or complete loss of an investment.</p>
            
            <p className="mt-4">As more fully set forth herein, Ascendant Academy, and its directors, officers, shareholders, employees, agents and affiliates, make no representation, warranty or guaranty as to the validity, adequacy, timeliness, accuracy, reliability or completeness of any data, content or information. You should independently analyze, review and confirm any such data, content or information.</p>
            
            <p className="mt-4">Ascendant Academy may express or utilize testimonials or descriptions of past performance, but such items are not indicative of future results or performance, or any representation, warranty or guaranty that any result will be obtained by you. Your results may differ materially from those expressed or utilized by Ascendant Academy due to a number of factors.</p>
            
            <p className="mt-4 font-bold">COMMODITY FUTURES TRADING COMMISSION RULE 4.41: Hypothetical performance results have many inherent limitations, some of which are described below. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown, in fact, there are frequently sharp differences between hypothetical performance results and the actual results subsequently achieved by any particular trading program. One of the limitations of hypothetical performance results is that they are generally prepared with the benefit of hindsight, in addition, hypothetical trading does not involve financial risk, and no hypothetical trading record can completely account for the impact of financial risk in actual trading. For example, the ability to withstand losses or adhere to a particular trading program in spite of trading losses are material points which can also adversely affect actual trading results. There are numerous other factors related to the markets in general or to the implementation of any specific trading program which cannot be fully accounted for in the preparation of hypothetical performance results and all of which can adversely affect actual trading results.</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Testimonials Disclaimer</h3>
            <p>In accordance with 16 CFR Part 255 and Federal Trade Commission Guidelines concerning use of endorsements and testimonials in marketing and advertising, please be aware of the following:</p>
            
            <p className="mt-4">Endorsements, testimonials or descriptions of past performance from other customers or members are based upon their individual experiences and results with the Site, and the products and services of Ascendant Academy. These results and performances are not typical, and you should not expect to achieve the same or similar results or performance, and your results and performance are likely to vary or differ materially. The endorsements, testimonials or descriptions of past performance are individual experiences, reflecting real life experiences of customers or members, and are not representative of the results and performances of all customers and members.</p>
            
            <p className="mt-4">Endorsements, testimonials or descriptions of past performance appearing on the Site were received via text, audio or video submission from customers or members. The endorsements, testimonials or descriptions of past performance (text, audio and/or video) are verbatim except for correction of grammatical or typing errors and editing for length. In other words, not the whole message received by the customer or member may be displayed, when it seemed lengthy or not all content seemed relevant for the general public. No endorsements, testimonials or descriptions of customers or members that appear on the Site involved payment or compensation therefor.</p>
            
            <p className="mt-4">Penny Pips's experience with trading is not typical, nor is the experience of individuals featured in testimonials. They are experienced traders. Becoming an experienced trader takes hard work, dedication and a significant amount of time.</p>
            
            <p className="mt-4">We do not track the typical results of our current or past students. As a provider of educational courses, we do not have access to the personal trading accounts or brokerage statements of our customers. Available research data suggests that most day traders are not profitable.</p>
            
            <p className="mt-4">In a research paper published in 2014 titled "Do Day Traders Rationally Learn About Their Ability?", professors from the University of California studied 3.7 billion trades from the Taiwan Stock Exchange between 1992-2006 and found that only 9.81% of day trading volume was generated by predictably profitable traders and that these predictably profitable traders constitute less than 3% of all day traders on an average day. *Citation 1</p>
            
            <p className="mt-4">In a 2005 article published in the Journal of Applied Finance titled "The Profitability of Active Stock Traders" professors at the University of Oxford and the University College Dublin found that out of 1,146 brokerage accounts day trading the U.S. markets between March 8, 2000 and June 13, 2000, only 50% were profitable with an average net profit of $16,619. *Citation 2</p>
            
            <p className="mt-4">In a 2003 article published in the Financial Analysts Journal titled "The Profitability of Day Traders", professors at the University of Texas found that out of 334 brokerage accounts day trading the U.S. markets between February 1998 and October 1999, only 35% were profitable and only 14% generated profits in excess of than $10,000. *Citation 3</p>
            
            <p className="mt-4">The range of results in these three studies exemplify the challenge of determining a definitive success rate for day traders. At a minimum, these studies indicate at least 50% of aspiring day traders will not be profitable. This reiterates that consistently making money trading stocks is not easy. Day Trading is a high risk activity and can result in the loss of your entire investment. Any trade or investment is at your own risk.</p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-3">Third Party Websites</h3>
            <p>The Site, and other products and services of Ascendant Academy, may contain links to other websites or applications. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party. Ascendant Academy has not reviewed all of the sites linked to or from the Site, or other products and services of Ascendant Academy, and is not responsible for the content of any such linked website. We do not exercise control over third party websites. Your use of links to other websites is at your own risk. We are not responsible for third party sites linked from the Site, or other products and services of Ascendant Academy, nor do we make any representation or warranties, express or implied, with respect to any such website, any content of such websites, or any products or services offered by any such websites, including but not limited to, accuracy, completeness, reliability, suitability, non-infringement, merchantability or fitness for a particular purpose.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">X. Limitations of Liability</h2>
            <p className="font-bold">WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, ASCENDANT ACADEMY, AND ITS DIRECTORS, OFFICERS, SHAREHOLDERS, EMPLOYEES, AGENTS AND AFFILIATES, SHALL NOT BE LIABLE TO YOU, UNDER ANY LEGAL OR EQUITABLE THEORY, FOR (A) ANY CONSEQUENTIAL, INCIDENTAL, PUNITIVE, EXEMPLARY, SPECIAL OR INDIRECT DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION LOST PROFITS, REVENUES AND BUSINESS, ARISING OUT OF, UNDER OR RELATING TO THESE TERMS AND CONDITIONS, YOUR USE OF THE SITE OR OTHERWISE RELATED TO OR ARISING FROM THE PRODUCTS OR SERVICES OF ASCENDANT ACADEMY, OR (B) ANY DAMAGES OF ANY KIND ARISING OUT OF, UNDER OR RELATING TO THE SITE OR OTHERWISE RELATED TO OR ARISING FROM THE PRODUCTS OR SERVICES OF ASCENDANT ACADEMY, IN EXCESS OF THREE TIMES THE MOST RECENT MONTHLY FEE PAID BY YOU IN CONNECTION WITH THE SITE, IF ANY, OR $250, WHICHEVER AMOUNT IS GREATER.</p>
            
            <p className="mt-4 font-bold">THIS LIMITATION OF LIABILITY SHALL APPLY REGARDLESS OF WHETHER THE LIMITED REMEDIES PROVIDED HEREIN FAIL OF THEIR ESSENTIAL PURPOSE, AND SHALL NOT APPLY TO ANY DAMAGE TO YOU INTENTIONALLY CAUSED BY ASCENDANT ACADEMY IN VIOLATION OF THESE TERMS AND CONDITIONS OR APPLICABLE LAW, OR AS OTHERWISE MANDATED BY APPLICABLE LAW THAT CANNOT BE DISCLAIMED BY THESE TERMS AND CONDITIONS.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XI. Indemnification</h2>
            <p>You shall, and hereby agree to, indemnify and hold harmless, Ascendant Academy, and its officers, directors, shareholders, employees, agents and affiliates, from any and all claims, losses, damages, liabilities and any other costs and expenses (including attorneys' fees), arising from or related to your (i) breach of a representation or warranty contained in these Terms and Conditions, (ii) breach of, or failure to comply with, any term contained in these Terms and Conditions, (iii) use of the Site or any products or services of Ascendant Academy, or (iv) use of, access to or other activity engaged in, on, through, related to or in connection with the Site.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XII. Privacy and Personal Information</h2>
            <p>Ascendant Academy shall have the right to use and disclose any information provided by you through the Site, or other products or services of Ascendant Academy (including but not limited to information provided through e-mail) or made available through your use of the Site, for any lawful purpose, unless you indicate otherwise in accordance with the policies and procedures therefor of Ascendant Academy. In no event shall you be entitled to any compensation for the use of any of such information. Please see the Privacy Policy for further details.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XIII. Modifications</h2>
            <p>Ascendant Academy reserves the right to revise these Terms and Conditions at any time without notice. By using the Site, you are agreeing to be bound by the then-current version of these Terms and Conditions, and your continued use of the Site reaffirms your agreement to the then-current Terms and Conditions. You agree to consult the Site regularly for up-to-date information about these Terms and Conditions and the Privacy Policy.</p>
            
            <p className="mt-4">Ascendant Academy may make changes to the Site, and the other products and services of Ascendant Academy, at any time without notice. Ascendant Academy does not, however, make any commitment to update the Site, and the other products and services of Ascendant Academy.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XIV. Governing Law</h2>
            <p>Any claim under these Terms and Conditions or otherwise related to the Site or Ascendant Academy shall be governed by the laws of the State of Nevada without regard to its conflict of law provisions, and shall be exclusively resolved by a state or federal court located in Washoe County, Nevada. You agree to submit to the personal jurisdiction of the courts located within Washoe County, Nevada, or another location of Ascendant Academy's choosing, for the purpose of litigating all such claims. Notwithstanding the above, you agree that Ascendant Academy shall still be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction. Except as otherwise provided herein, you agree that any controversy or claim, whether at law or equity, arising out of or related to the provision of services or materials by Ascendant Academy, regardless of the date of accrual of such dispute, shall be resolved in its entirety by individual (not class-wide nor collective) binding arbitration.</p>
            
            <p className="mt-4">The Site, and the other products and services of Ascendant Academy, are solely directed to and intended for individuals residing in the United States. Those who choose to access and use the Site, and the other products and services of Ascendant Academy, from other locations do so at their own risk, and are responsible for compliance with all laws, rules and regulations applicable thereto. Ascendant Academy reserves the right to limit the availability of the Site, and any other products or services of Ascendant Academy, to any person, geographic area, or jurisdiction, in any manner and at any time, in its sole discretion.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XV. Severability</h2>
            <p>If any provision of these Terms and Conditions is found by a court of competent jurisdiction or arbitrator to be illegal, void, or unenforceable, the unenforceable provision will be modified so as to render it enforceable and effective to the maximum extent possible in order to effect the intention of the provision; and if a court or arbitrator finds the modified provision invalid, illegal, void or unenforceable, the validity, legality and enforceability of the remaining provisions of these Terms and Conditions will not be affected in any way.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XVI. Entire Agreement</h2>
            <p>You agree that these Terms and Conditions constitute the entire, complete and exclusive agreement between you and us regarding the Site and the products and services of Ascendant Academy, and supersedes all prior agreements and understandings, whether written or oral, or whether established by custom, practice, policy or precedent, with respect to the subject matter of these Terms and Conditions. The provisions of these Terms and Conditions shall survive any termination thereof indefinitely.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XVII. Waivers</h2>
            <p>Our failure to act with respect to a breach of these Terms and Conditions by you or others does not waive our right to act with respect to that breach or subsequent similar or other breaches.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">XVIII. Questions?</h2>
            <p>Questions about these Terms and Conditions should be addressed to support@ascendantacademy.ca. Questions about billing should be addressed to support@ascendantacademy.ca.</p>
            
            <p className="mt-4 font-bold">IF YOU DO NOT AGREE WITH ANY TERM OR PROVISION OF THESE TERMS AND CONDITIONS, PLEASE EXIT THE SITE IMMEDIATELY. PLEASE BE ADVISED THAT YOUR CONTINUED USE OF THIS SITE OR THE PRODUCTS OR INFORMATION PROVIDED THEREBY SHALL INDICATE YOUR CONSENT AND AGREEMENT TO THESE TERMS AND CONDITIONS.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">Sources</h2>
            <p><strong>Citation 1:</strong> Barber, Brad & Lee, Yong-Ill & Liu, Yu-Jane & Odean, Terrance. (2014). Do Day Traders Rationally Learn About Their Ability?. SSRN Electronic Journal. https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2535636</p>
            
            <p className="mt-4"><strong>Citation 2:</strong> Garvey, Ryan and Murphy, Anthony, The Profitability of Active Stock Traders. Journal of Applied Finance , Vol. 15, No. 2, Fall/Winter 2005. Available at SSRN: https://ssrn.com/abstract=908615</p>
            
            <p className="mt-4"><strong>Citation 3:</strong> Douglas J. Jordan & J. David Diltz (2003) The Profitability of Day Traders, Financial Analysts Journal, 59:6, 85-94, DOI: 10.2469/faj.v59.n6.2578</p>
          </section>
        </div>
      </div>

      <Footer />
    </main>
  );
}
